apiVersion: v1
kind: Service
metadata:
  name: plex-host-network-service
  namespace: media
spec:
  externalTrafficPolicy: Local
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 192.168.178.65
  ports:
  - name: plex-access
    nodePort: 32400
    port: 32400
    protocol: TCP
    targetPort: 32400
  selector:
    app.kubernetes.io/instance: plex
  sessionAffinity: None
  type: LoadBalancer