---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mail@marcel-lambacher.de
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    # - http01:
    #     ingress:
    #       class: traefik
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: digitalocean-token-secret
              key: digitalocean-token
        selector:
          dnsZones:
            - "cloud.lambacher.eu"