apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sealed-digitalocean-token-secret.json
  - https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.yaml
  - issuer-letsencrypt-prod.yaml
  - cert-prod-cloud-lambacher-eu.yaml
  - traefik-dynamic-config-map.yaml
  - traefik-config.yaml