apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - namespace.yaml
  # - sealed-digitalocean-token-secret.json
  # will be deployed via ansible, because argocd is dump...
  # - https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.yaml
  - issuer-letsencrypt-prod.yaml
  - cert-prod-masterloft-k8s-marcel-lambacher-de.yaml
  - traefik-dynamic-config-map.yaml
  - traefik-config.yaml

# helmCharts:
# - name: cert-manager
#   includeCRDs: true
#   valuesMerge: merge
#   valuesFile: values.yaml
#   releaseName: cert-manager
#   version: v1.9.1
#   repo: https://charts.jetstack.io