apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authelia
resources:
  - namespace.yaml
  - authelia-users-database.yaml
  - sealed-authelia-secrets.json
  - middleware.yaml

helmCharts:
- name: authelia
  includeCRDs: false
  valuesFile: values.yaml
  releaseName: authelia
  version: 0.8.38
  repo: https://charts.authelia.com