persistence:
  enabled: true
  storageClass: longhorn-single-replica

secret:
  existingSecret: "authelia-secrets"

pod:
  extraVolumeMounts:
  - name: authelia-users-database
    mountPath: "/config/users_database.yml"
    subPath: users_database.yml

  extraVolumes:
    - name: authelia-users-database
      secret:
        secretName: authelia-users-database

domain: masterloft.k8s.marcel-lambacher.de

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik

  subdomain: auth

  # TLS is deactived in ingress, since default cert of traefik will take care of it (TLS per default)
  tls:
    enabled: false
    # secret: masterloft-k8s-marcel-lambacher-de-tls

configMap:
  # identity_providers:
  #   oidc:
  #     enable_client_debug_messages: true
  #     enabled: true
  #     cors:
  #       endpoints:
  #         - authorization
  #         - token
  #         - revocation
  #         - introspection
  #     clients:
  #       - id: cf9ff4de45354bcd8fc8f83c1fb932f9
  #         description: GitOps
  #         sector_identifier: ''
  #         public: false
  #         authorization_policy: two_factor
  #         pre_configured_consent_duration: ''
  #         scopes:
  #           - openid
  #           - email
  #           - groups
  #           - profile
  #         redirect_uris:
  #           - https://gitops.masterloft.k8s.marcel-lambacher.de/oauth2/callback
  #           - https://openidconnect.net/callback
  #         # grant_types:
  #         #   - refresh_token
  #         #   - authorization_code
  #         # response_types:
  #         #   - code
  #         response_modes:
  #           - form_post
  #           - query
  #           - fragment
  #         userinfo_signing_algorithm: none

  session:
    redis:
      enabled: false

  authentication_backend:
    ldap:
      enabled: false

    file:
      enabled: true
      password:
        algorithm: argon2id
        iterations: 1
        key_length: 32
        salt_length: 16
        memory: 1024
        parallelism: 8

  storage:
    local:
      enabled: true

    postgres:
      enabled: false

    mysql:
      enabled: false
      # host: mariadb.database.svc.cluster.local

  notifier:
    filesystem:
      enabled: true

    smtp:
      enabled: false