---
- name: Download kubectl binary
  ansible.builtin.get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"
    checksum: "{{ kubectl_checksum }}"
    dest: "/tmp"
    mode: 0600
  tags:
    - kubectl

- name: Copy kubectl binary to destination directory
  ansible.builtin.copy:
    src: "/tmp/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: "0755"
    owner: "root"
    group: "root"
    remote_src: true
  with_items:
    - kubectl