---
- name: Download the archive file.
  become: true
  become_user: root
  get_url:
    url: 'https://github.com/vmware-tanzu/velero/releases/download/{{ velero_version }}/velero-{{ velero_version }}-linux-amd64.tar.gz'
    dest: /tmp/velero-{{ velero_version }}-linux-amd64.tar.gz
    checksum: '{{ velero_checksum }}'
    mode: 0644

- name: Create velero app directory
  become: true
  become_user: root
  file:
    path: '/usr/local/bin/velero-{{ velero_version }}-linux-amd64'
    state: directory
    mode: 0755

- name: Unarchive velero
  become: true
  unarchive:
    remote_src: true
    src: /tmp/velero-{{ velero_version }}-linux-amd64.tar.gz
    dest: '/usr/local/bin/'
    creates: '/usr/local/bin/velero-{{ velero_version }}-linux-amd64/velero'

- name: Make a link to the velero executable
  file:
    src: '/usr/local/bin/velero-{{ velero_version }}-linux-amd64/velero'
    dest: '/usr/local/bin/velero'
    state: link
  become: true
  become_user: root