apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: database
spec:
  releaseName: mariadb
  chart:
    spec:
      chart: mariadb
      version: 11.3.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system

  interval: 30s
  timeout: 3m0s

  install:
    timeout: 3m0s
    disableWait: false
    replace: true

  upgrade:
    timeout: 3m0s
    disableWait: false
    force: true

  valuesFrom:
    - kind: Secret
      name: mariadb-initdb-secret

  values:
    global:
      storageClass: local-path-ssd-auto-backup
    auth:
      username: marlam
      database: masterloft 
      existingSecret: mariadb-init-secrets