---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: masterloft-k8s-marcel-lambacher-de
  namespace: kube-system
spec:
  secretName: masterloft-k8s-marcel-lambacher-de-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.masterloft.k8s.marcel-lambacher.de"
  dnsNames:
  - "masterloft.k8s.marcel-lambacher.de"
  - "*.masterloft.k8s.marcel-lambacher.de"