configmap:
  name: local-path-ssd-auto-backup-config

storageClass:
  name: local-path-ssd-auto-backup

nodePathMap:
  - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
    paths:
      - /opt/k3s/local-path-provisioner/local-path-ssd-auto-backup