apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  releaseName: vaultwarden
  chart:
    spec:
      # chart: onechart 
      # version: 0.40.0
      # sourceRef:
      #   kind: HelmRepository
      #   name: onechart
      #   namespace: flux-system
      chart: charts/onechart
      sourceRef:
        kind: GitRepository
        name: onechart-fork
        namespace: flux-system

  interval: 30s
  timeout: 3m0s

  install:
    timeout: 3m0s
    disableWait: false
    replace: true

  upgrade:
    timeout: 3m0s
    disableWait: false
    force: true

  values:
    resources:
      ignore: true

    image:
      repository: vaultwarden/server
      tag: latest

    ingress:
      annotations:
        kubernetes.io/ingress.class: traefik
      host: vaultwarden.cloud.lambacher.eu
      # TLS is deactived in ingress, since default cert of traefik will take care of it (TLS per default)
      tlsEnabled: false

    replicas: 1

    containerPort: 80

    probe:
      enabled: true
      path: "/"
      settings:
        initialDelaySeconds: 0
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 3
        failureThreshold: 3

    livenessProbe:
      enabled: true
      path: "/"
      settings:
        initialDelaySeconds: 0
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 3
        failureThreshold: 3

    volumes:
      - name: data
        path: /data
        size: 1Gi
        storageClass: local-path-ssd-auto-backup
        pvcAnnotations: 
          helm.sh/resource-policy: keep