apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      websecure:
        tls:
          enabled: true
      web:
        redirectTo: websecure

    providers:
      kubernetesCRD:
        allowCrossNamespace: true

    # volumes:
    #   - name: masterloft-k8s-marcel-lambacher-de-tls
    #     mountPath: /certs
    #     type: secret
    #   - name: traefik-dynamic-config
    #     mountPath: /config
    #     type: configMap

    # additionalArguments:
    #   - --providers.file.filename=/config/dynamic.yaml    