apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: seafile
  namespace: seafile
spec:
  releaseName: seafile
  chart:
    spec:
      chart: seafile
      version: 3.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 30s
  install:
    remediation:
      retries: 3
  values:
    env:
      SEAFILE_SERVER_HOSTNAME: seafile.masterloft.k8s.marcel-lambacher.de
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: seafile.masterloft.k8s.marcel-lambacher.de
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: seafile
                  port: 80

        tls:
        - hosts:
          - seafile.masterloft.k8s.marcel-lambacher.de
          secretName: masterloft-k8s-marcel-lambacher-de-tls
