apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: nigthly-backup
  namespace: velero
spec:
  schedule: '@midnight'
  template:
    hooks: {}
    includeClusterResources: true
    includedNamespaces:
    - '*'
    ttl: 360h0m0s
  useOwnerReferencesInBackup: false