apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nextcloud
resources:
  - namespace.yaml
  - sealed-nextcloud-admin-secret.json
  - redirect-card-and-cal-dav.yaml
  - sealed-nextcloud-redis-auth.json
  - sealed-nextcloud-postgresql-auth.json

commonAnnotations:
  backup.velero.io/backup-volumes: nextcloud-data

helmCharts:
- name: nextcloud
  includeCRDs: false
  valuesFile: values.yaml
  releaseName: nextcloud
  version: 3.3.3
  repo: https://nextcloud.github.io/helm/

# patches:
# - path: patch-deployment-security-context.yaml
#   target:
#     kind: Deployment
#     labelSelector: app.kubernetes.io/name=nextcloud
