ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik

securityContext:
  runAsUser: 1000
  runAsGroup: 1001
  runAsNonRoot: true

nextcloud:
  host: nextcloud.masterloft.k8s.marcel-lambacher.de
  existingSecret:
    enabled: true
    secretName: nextcloud-admin-secret
    usernameKey: username
    passwordKey: password

  extraVolumes:
  - name: masterloft-nas-storage
    hostPath:
      path: /data
      type: ""

  extraVolumeMounts:
   - name: masterloft-nas-storage
     mountPath: /masterloft-nas-storage

  extraSecurityContext:
    runAsUser: 1000
    runAsGroup: 1001
    runAsNonRoot: true

persistence:
  enabled: true
  storageClass: longhorn-single-replica