ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: nextcloud-redirect-card-and-cal-dav@kubernetescrd

# securityContext:
#   runAsUser: 1000
#   runAsGroup: 1001
#   runAsNonRoot: true

lifecycle:
  # postStartCommand: ["/bin/sh", "-c", "apt install smbclient libsmbclient-dev; pecl install smbclient; docker-php-ext-enable smbclient"]
  postStartCommand: ["/bin/sh", "-c", "apt update && apt install -y smbclient libsmbclient-dev"]

nextcloud:
  host: nextcloud.masterloft.k8s.marcel-lambacher.de
  existingSecret:
    enabled: true
    secretName: nextcloud-admin-secret
    usernameKey: username
    passwordKey: password

  configs:
    traefik.config.php: |-
      <?php
      $CONFIG = array (
        'overwrite.cli.url' => 'https://nextcloud.masterloft.k8s.marcel-lambacher.de',
        'overwriteprotocol' => 'https'
      );

  extraVolumes:
  - name: masterloft-nas-storage
    hostPath:
      path: /data
      type: ""

  extraVolumeMounts:
   - name: masterloft-nas-storage
     mountPath: /masterloft-nas-storage

  # extraSecurityContext:
  #   runAsUser: 1000
  #   runAsGroup: 1001
  #   runAsNonRoot: true

persistence:
  enabled: true
  storageClass: longhorn-single-replica

redis:
  global:
    storageClass: longhorn-single-replica
  architecture: standalone
  enabled: true
  auth:
    enabled: true
    existingSecret: nextcloud-redis-auth
    existingSecretPasswordKey: password

externalDatabase:
  enabled: true
  type: postgresql
  host: database.postgresql.svc.cluster.local
  database: nextcloud
  existingSecret:
    enabled: true
    secretName: nextcloud-postgresql-auth
    usernameKey: username
    passwordKey: password