ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik

nextcloud:
  host: nextcloud.masterloft.k8s.marcel-lambacher.de
  existingSecret:
    enabled: true
    secretName: nextcloud-admin-secret
    usernameKey: username
    passwordKey: password

  extraVolumes:
   - name: nfs
     nfs:
       server: "192.168.178.65"
       path: "/Storage"
       readOnly: false
  extraVolumeMounts:
   - name: nfs
     mountPath: "/nfs-masterloft-storage"

persistence:
  enabled: true
  storageClass: longhorn-single-replica