apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - sealed-postgresql-secrets.json
  - sealed-postgresql-initdb.json

commonAnnotations:
  backup.velero.io/backup-volumes: config

helmCharts:
- name: postgresql
  includeCRDs: false
  valuesFile: values.yaml
  releaseName: postgresql
  version: 11.9.5
  repo: https://charts.bitnami.com/bitnami