apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/apps/media/plex
    repoURL: 'https://github.com/Marcel-Lambacher/Masterloft.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true