apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authelia
resources:
  - namespace.yaml
  - release.yaml
  - authelia-users-database.yaml
  - sealed-authelia-secrets.json
  - middleware.yaml