apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  releaseName: authelia
  chart:
    spec:
      chart: authelia
      version: 0.8.38
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system

  interval: 30s
  timeout: 3m0s

  install:
    timeout: 3m0s
    disableWait: false
    replace: true

  upgrade:
    timeout: 3m0s
    disableWait: false
    force: true

  values:
    domain: masterloft.k8s.marcel-lambacher.de

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-prod

      subdomain: auth

      tls:
        secret: masterloft-k8s-marcel-lambacher-de-tls

    configMap:
      session:
        redis:
          enabled: false

      authentication_backend:
        ldap:
          enabled: false

        file:
          enabled: true
          password:
            algorithm: sha512
            iterations: 100000

      storage:
        local:
          enabled: true

        postgres:
          enabled: false

      notifier:
        filesystem:
          enabled: true

        smtp:
          enabled: false