apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  releaseName: authelia
  chart:
    spec:
      chart: authelia
      version: 0.8.38
      sourceRef:
        kind: HelmRepository
        name: authelia
        namespace: flux-system

  interval: 30s
  timeout: 3m0s

  install:
    timeout: 3m0s
    disableWait: false
    replace: true

  upgrade:
    timeout: 3m0s
    disableWait: false
    force: true

  values:
    persistence:
      enabled: true
      storageClass: "local-path-ssd-auto-backup"

    secret:
      existingSecret: "authelia-secrets"

    pod:
      extraVolumeMounts:
      - name: authelia-users-database
        mountPath: "/config/users_database.yml"
        subPath: users_database.yml

      extraVolumes:
        - name: authelia-users-database
          secret:
            secretName: authelia-users-database

    domain: masterloft.k8s.marcel-lambacher.de

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-prod

      subdomain: auth

      tls:
        secret: masterloft-k8s-marcel-lambacher-de-tls

    configMap:
      session:
        redis:
          enabled: false

      authentication_backend:
        ldap:
          enabled: false

        file:
          enabled: true
          password:
            algorithm: argon2id
            iterations: 1
            key_length: 32
            salt_length: 16
            memory: 1024
            parallelism: 8

      storage:
        local:
          enabled: false

        postgres:
          enabled: false

        mysql:
          enabled: true
          host: mariadb.database.svc.cluster.local

      notifier:
        filesystem:
          enabled: true

        smtp:
          enabled: false