apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

commonAnnotations:
  backup.velero.io/backup-volumes: data

helmCharts:
- name: onechart
  includeCRDs: false
  valuesMerge: merge
  valuesFile: values.yaml
  valuesInline:
    image:
      repository: linuxserver/radarr 
      tag: 4.1.0
  releaseName: radarr
  version: 0.46.0
  repo: https://marcel-lambacher.github.io/onechart