apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

commonAnnotations:
  backup.velero.io/backup-volumes: data

commonLabels:
  app.kubernetes.io/name: prowlarr

helmCharts:
- name: onechart
  includeCRDs: false
  valuesFile: values.yaml
  releaseName: prowlarr
  version: 0.46.0
  repo: https://marcel-lambacher.github.io/onechart