apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: local-path-provisioner
resources:
  - namespace.yaml
  - local-path-ssd-auto-backup-release.yaml
  - local-path-ssd-no-backup-release.yaml