apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
  - namespace.yaml
  - pool.yaml

helmCharts:
- name: metallb
  includeCRDs: true
  releaseName: metallb
  version: 0.13.7
  repo: https://metallb.github.io/metallb