apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard
  namespace: adguard
spec:
  releaseName: adguard
  chart:
    spec:
      chart: adguard-home
      version: 5.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system

  interval: 30s
  timeout: 10m0s

  install:
    timeout: 10m0s
    disableWait: false
    replace: true

  upgrade:
    timeout: 10m0s
    disableWait: false
    force: true

  values:
    persistence:
      config:
        enabled: true
        storageClass: local-path-ssd-auto-backup 

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/router.middlewares: adguard-adguard-basic-auth@kubernetescrd
        hosts:
          - host: adguard.masterloft.k8s.marcel-lambacher.de
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: adguard-adguard-home
                  port: 3000

        tls:
        - hosts:
          - adguard.masterloft.k8s.marcel-lambacher.de
          secretName: masterloft-k8s-marcel-lambacher-de-tls

