apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
resources:
  - namespace.yaml
  - ingress.yaml

helmCharts:
- name: podinfo
  includeCRDs: false
  releaseName: podinfo
  repo: https://stefanprodan.github.io/podinfo

patches:
  - target:
      kind: (StatefulSet|Deployment|Job|Pod)
    patch: |-
      kind: not-important
      metadata:
        name: not-important
      spec:
        template:
          spec:
            tolerations:
            - key: "cloud.lambacher.eu/location"
              value: "onpremise"
              operator: "Equal"
              effect: "NoSchedule"

            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                  - matchExpressions:
                    - key: cloud.lambacher.eu/location
                      operator: In
                      values:
                      - onpremise