apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pihole
resources:
  - namespace.yaml
  - seaeld-pihole-admin-secret.json

commonAnnotations:
  backup.velero.io/backup-volumes: config

helmCharts:
- name: pihole
  includeCRDs: false
  valuesFile: values.yaml
  releaseName: pihole
  version: 2.9.3
  repo: https://mojo2600.github.io/pihole-kubernetes/