apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-admin-path-prefix-middleware
  namespace: pihole
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /admin/