apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    tolerations:
    - key: "cloud.lambacher.eu/location"
      value: "onpremise"
      operator: "Equal"
      effect: "NoSchedule"

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: cloud.lambacher.eu/location
              operator: In
              values:
              - onpremise
              
    ports:
      websecure:
        tls:
          enabled: true
      web:
        redirectTo: websecure

    providers:
      kubernetesCRD:
        allowCrossNamespace: true

    volumes:
      - name: cloud-lambacher-eu-tls
        mountPath: /certs
        type: secret
      - name: traefik-dynamic-config
        mountPath: /config
        type: configMap

    additionalArguments:
      - --providers.file.filename=/config/dynamic.yaml    