---

- name: install wireguard package
  apt:
    name: wireguard
    state: present
    update_cache: yes

- name: enable and persist ip forwarding
  when: inventory_hostname in groups['masterloft-remote-tunnel']
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    sysctl_set: yes
    reload: yes

- name: create client wireguard config
  template:
    dest: /etc/wireguard/wg0.conf
    src: "{{ wireguard_config_template_path }}"
    owner: root
    group: root
    mode: '0600'
  # notify: reload wireguard config

- name: start wireguard and enable on boot
  systemd:
    name: wg-quick@wg0
    enabled: yes
    state: started

# handlers:
# # Reloads config without disrupting current peer sessions, but does not
# # re-run PostUp commands. Notify this handler on server config changes.
# - name: reload wireguard config
#   shell: wg syncconf wg0 <(wg-quick strip wg0)
#   args:
#     executable: /bin/bash