apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn
resources:
  - namespace.yaml
  - storageclass.yaml

helmCharts:
- name: longhorn
  includeCRDs: false
  valuesFile: values.yaml
  releaseName: longhorn
  version: 1.5.0
  repo: https://charts.longhorn.io

patches:
  - patch: |-
      kind: not-important
      metadata:
        name: not-important
      spec:
        template:
          spec:
            nodeSelector:
              cloud.lambacher.eu/location: onpremise
    target:
      kind: (StatefulSet|Deployment|Job|Pod)