apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn
resources:
  - namespace.yaml

helmCharts:
- name: longhorn
  includeCRDs: false
  valuesFile: values.yaml
  releaseName: longhorn
  version: 1.3.1
  repo: https://charts.longhorn.io