apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn
resources:
  - namespace.yaml
  - storageclass-important.yaml
  - storageclass-temp.yaml
  - sealed-s3-secret.json
  - longhorn-important-backup-default.yaml
  - longhorn-important-snap-default.yaml

helmCharts:
- name: longhorn
  includeCRDs: false
  valuesFile: values.yaml
  releaseName: longhorn
  version:  1.4.1
  repo: https://charts.longhorn.io