ingress:
  ## Set to true to enable ingress record generation
  enabled: true

  ## Add ingressClassName to the Ingress
  ## Can replace the kubernetes.io/ingress.class annotation on v1.18+
  ingressClassName: ~
  annotations:
    kubernetes.io/ingress.class: traefik
    # traefik.ingress.kubernetes.io/router.middlewares: authelia-forwardauth-authelia@kubernetescrd

  host: longhorn.cloud.lambacher.eu

global:
  cattle:
    systemDefaultRegistry: ""
    windowsCluster:
      enabled: false
      tolerations:
      - key: "cloud.lambacher.eu/location"
        value: "onpremise"
        effect: "NoSchedule"
        operator: "Equal"
      nodeSelector:
        cloud.lambacher.eu/location: "onpremise"
      defaultSetting:
        taintToleration: cloud.lambacher.eu/location=onpremise:NoSchedule
        systemManagedComponentsNodeSelector: cloud.lambacher.eu/location:onpremise

defaultSettings:
  taintToleration: cloud.lambacher.eu/location=onpremise:NoSchedule
  systemManagedComponentsNodeSelector: cloud.lambacher.eu/location:onpremise
  backupTarget: s3://k8s-longhorn-backup@nyc3/main
  backupTargetCredentialSecret: s3-secret

persistence:
  defaultNodeSelector:
    enable: true
    selector: cloud.lambacher.eu/location:onpremise

longhornManager:
  tolerations: 
  - key: "cloud.lambacher.eu/location"
    operator: "Equal"
    value: "onpremise"
    effect: "NoSchedule"
  nodeSelector:
    cloud.lambacher.eu/location: onpremise

longhornDriver:
  tolerations: 
  - key: "cloud.lambacher.eu/location"
    operator: "Equal"
    value: "onpremise"
    effect: "NoSchedule"
  nodeSelector:
    cloud.lambacher.eu/location: onpremise

longhornConversionWebhook:
  tolerations: 
  - key: "cloud.lambacher.eu/location"
    operator: "Equal"
    value: "onpremise"
    effect: "NoSchedule"
  nodeSelector:
    cloud.lambacher.eu/location: onpremise

longhornAdmissionWebhook:
  tolerations: 
  - key: "cloud.lambacher.eu/location"
    operator: "Equal"
    value: "onpremise"
    effect: "NoSchedule"
  nodeSelector:
    cloud.lambacher.eu/location: onpremise

longhornRecoveryBackend:
  tolerations: 
  - key: "cloud.lambacher.eu/location"
    operator: "Equal"
    value: "onpremise"
    effect: "NoSchedule"
  nodeSelector:
    cloud.lambacher.eu/location: onpremise

longhornUI:
  tolerations: 
  - key: "cloud.lambacher.eu/location"
    operator: "Equal"
    value: "onpremise"
    effect: "NoSchedule"
  nodeSelector:
    cloud.lambacher.eu/location: onpremise