apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  releaseName: sonarr
  chart:
    spec:
      # chart: onechart 
      # version: 0.40.0
      # sourceRef:
      #   kind: HelmRepository
      #   name: onechart
      #   namespace: flux-system
      chart: charts/onechart
      sourceRef:
        kind: GitRepository
        name: onechart-fork
        namespace: flux-system


  interval: 30s
  timeout: 3m0s

  install:
    timeout: 3m0s
    disableWait: false
    replace: true

  upgrade:
    timeout: 3m0s
    disableWait: false
    force: true

  values:
    vars:
      PUID: 1000
      PGID: 1000

    resources:
      ignore: true

    image:
      repository: linuxserver/sonarr 
      tag: 3.0.9

    ingress:
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.middlewares: authelia-forwardauth-authelia@kubernetescrd
      host: sonarr.cloud.lambacher.eu
      # TLS is deactived in ingress, since default cert of traefik will take care of it (TLS per default)
      tlsEnabled: false

    replicas: 1

    containerPort: 8989

    probe:
      enabled: false
      path: "/"
      settings:
        initialDelaySeconds: 0
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 3
        failureThreshold: 3

    livenessProbe:
      enabled: false
      path: "/"
      settings:
        initialDelaySeconds: 0
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 3
        failureThreshold: 3

    volumes:
      - name: config
        path: /config
        size: 1Gi
        storageClass: local-path-ssd-auto-backup
        pvcAnnotations: 
          helm.sh/resource-policy: keep

      - name: data
        path: /data
        hostPath:
          path: /data