---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: masterloft-k8s-marcel-lambacher-de
  namespace: kube-system
spec:
  secretName: cloud-lambacher-eu-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.cloud.lambacher.eu"
  dnsNames:
  - "cloud.lambacher.eu"
  - "*.cloud.lambacher.eu"