---

- name: Apply argocd namespace 1/3
  template:
    dest: /tmp/create-argocd-namespace.yaml
    src: "create-argocd-namespace.yaml.j2"

- name: Apply argocd namespace 2/3
  become: true
  become_user: "{{ ansible_ssh_user }}"
  command: "kubectl apply -f /tmp/create-argocd-namespace.yaml"

- name: Apply argocd  namespace 3/3
  file:
    path: /tmp/create-argocd-namespace.yaml
    state: absent

- name: Apply argocd secrets private key  1/3
  template:
    dest: /tmp/create-sealed-argocd-secret.yaml
    src: "create-sealed-argocd-secret.yaml.j2"

- name: Apply argocd secrets private key 2/3
  become: true
  become_user: "{{ ansible_ssh_user }}"
  command: "kubectl apply -f /tmp/create-sealed-argocd-secret.yaml"

- name:  Apply argocd secrets private key 3/3
  file:
    path: /tmp/create-sealed-argocd-secret.yaml
    state: absent

- name: Apply argocd admin secrets  1/3
  template:
    dest: /tmp/create.argocd-initial-admin-secret.yaml
    src: "create.argocd-initial-admin-secret.yaml.j2"

- name: Apply argocd admin secrets 2/3
  become: true
  become_user: "{{ ansible_ssh_user }}"
  command: "kubectl apply -f /tmp/create.argocd-initial-admin-secret.yaml"

- name:  Apply argocd admin secrets 3/3
  file:
    path: /tmp/create.argocd-initial-admin-secret.yaml
    state: absent

- name: Apply argocd kustomization  1/3
  copy:
    src: argocd/
    dest: /tmp/argocd

- name: Apply argocd kustomization  2/3
  become: true
  become_user: "{{ ansible_ssh_user }}"
  command: "kubectl apply -k /tmp/argocd"

- name: Apply argocd kustomization  3/3
  file:
    path: /tmp/argocd
    state: absent