---

- name: Apply cert-manager
  become: true
  become_user: "{{ ansible_ssh_user }}"
  command: "kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v{{ cert_manager_version }}/cert-manager.yaml"

- name: Apply sealed digital ocean key  1/3
  template:
    dest: /tmp/create-sealed-digitalocean-token-secret.json
    src: "create-sealed-digitalocean-token-secret.json.j2"

- name: Apply sealed digital ocean key 2/3
  become: true
  become_user: "{{ ansible_ssh_user }}"
  command: "kubectl apply -f /tmp/create-sealed-digitalocean-token-secret.json"

- name: Apply sealed digital ocean key  3/3
  file:
    path: /tmp/create-sealed-digitalocean-token-secret.json
    state: absent