---
- name: Download sealed-secrets archive file
  become: true
  become_user: root
  get_url:
    url: 'https://github.com/bitnami-labs/sealed-secrets/releases/download/{{ sealed_secrets_version }}/kubeseal-{{ sealed_secrets_version[1:] }}-linux-amd64.tar.gz'
    dest: /tmp/kubeseal-{{ sealed_secrets_version }}-linux-amd64.tar.gz
    checksum: '{{ sealed_secrets_checksum }}'
    mode: 0644

- name: install unarchive module dependencies (apt, yum, dnf, zypper)
  become: true
  package:
    name:
      - tar
      - unzip
      - gzip
    state: present
  when: ansible_pkg_mgr in ('apt', 'yum', 'dnf', 'zypper')

- name: Create sealed-secrets app directory
  become: true
  become_user: root
  file:
    path: '/usr/local/bin/kubeseal-{{ sealed_secrets_version }}-linux-amd64'
    state: directory
    mode: 0755

- name: Unarchive sealed-secrets
  become: true
  unarchive:
    remote_src: true
    src: /tmp/kubeseal-{{ sealed_secrets_version }}-linux-amd64.tar.gz
    dest: '/usr/local/bin/kubeseal-{{ sealed_secrets_version }}-linux-amd64'
    creates: '/usr/local/bin/kubeseal-{{ sealed_secrets_version }}-linux-amd64/kubeseal'

- name: Make a link to the sealed secret executable
  file:
    src: '/usr/local/bin/kubeseal-{{ sealed_secrets_version }}-linux-amd64/kubeseal'
    dest: '/usr/local/bin/kubeseal'
    state: link
  become: true
  become_user: root

- name: Create temp cert-manager directory
  file:
    path: '/tmp/sealed-secrets'
    state: directory
    mode: 0755

- name: Copy sealed-secrets templates
  template:
    src: "{{ item }}"
    dest: /tmp/sealed-secrets/{{ item | basename | regex_replace('\.j2$', '') }}
  with_fileglob:
    - ../templates/sealed-secrets/*.*

- name: Kustomize sealed-secrets
  become: true
  become_user: "{{ ansible_ssh_user }}"
  command: "kubectl apply -k /tmp/sealed-secrets"