---
- name: Check if velero app exists
  become: true
  stat:
    path: '/usr/local/bin/velero'
  changed_when: false
  register: velero_binary

- when: not velero_binary.stat.exists
  block:
    - name: Download the archive file.
      become: true
      become_user: root
      get_url:
        url: 'https://github.com/vmware-tanzu/velero/releases/download/{{ velero_version }}/velero-{{ velero_version }}-linux-amd64.tar.gz'
        dest: /tmp/velero-{{ velero_version }}-linux-amd64.tar.gz
        checksum: '{{ velero_checksum }}'
        mode: 0644

    - name: Create velero app directory
      become: true
      become_user: root
      file:
        path: '/usr/local/bin/velero-{{ velero_version }}-linux-amd64'
        state: directory
        mode: 0755

    - name: Unarchive velero
      become: true
      unarchive:
        remote_src: true
        src: /tmp/velero-{{ velero_version }}-linux-amd64.tar.gz
        dest: '/usr/local/bin/'
        creates: '/usr/local/bin/velero-{{ velero_version }}-linux-amd64/velero'

    - name: Make a link to the velero executable
      file:
        src: '/usr/local/bin/velero-{{ velero_version }}-linux-amd64/velero'
        dest: '/usr/local/bin/velero'
        state: link
      become: true
      become_user: root

    - name: Copy velero secrets file
      template:
        dest: /tmp/velero-secrets
        src: "velero-secrets.j2"

    - name: Bootstrap velero
      become: true
      become_user: "{{ ansible_ssh_user }}"
      command: |
        velero install \
            --provider azure \
            --plugins velero/velero-plugin-for-microsoft-azure:v1.5.0 \
            --bucket velero \
            --secret-file /tmp/velero-secrets \
            --backup-location-config resourceGroup={{ velero_azure_backup_account_resource_group }},storageAccount={{ velero_azure_backup_account_name }},storageAccountKeyEnvVar=AZURE_STORAGE_ACCOUNT_ACCESS_KEY,subscriptionId={{ velero_azure_backup_account_subscription }}] \
            --use-volume-snapshots=false
            --use-restic

    - name: Restore from last backup 
      become: true
      become_user: "{{ ansible_ssh_user }}"
      command: |
        velero restore create --from-backup {{ velero_last_backup_name }}


  always:
    - name: Remove velero archive
      become: true
      become_user: root
      file:
        path: /tmp/velero-{{ velero_version }}-linux-amd64.tar.gz
        state: absent

    - name: Delete velero secrets file
      file:
        path: /tmp/velero-secrets
        state: absent