apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: database
spec:
  releaseName: postgresql
  chart:
    spec:
      chart: postgresql
      version: 11.8.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system

  interval: 30s
  timeout: 3m0s

  install:
    timeout: 3m0s
    disableWait: false
    replace: true

  upgrade:
    timeout: 3m0s
    disableWait: false
    force: true

  valuesFrom:
    - kind: Secret
      name: mariadb-initdb-secret

  values:
    primary:
      extraVolumeMounts:
        - name: postgresql-initdb
          mountPath: /docker-entrypoint-initdb.d/

      extraVolumes :
        - name: postgresql-initdb
          secret:
            secretName: postgresql-initdb
            
    auth:
      enablePostgresUser: true
    global:
      storageClass: local-path-ssd-auto-backup

      postgresql:
        auth:
          existingSecret: postgresql
          secretKeys:
            adminPasswordKey: postgres-password
            replicationPasswordKey: replication-password