---

- name: "[POST] Lock SSH key"
  command: ssh-add -d /tmp/id_ansible
  delegate_to: 127.0.0.1
  become: no
  changed_when: no
  ignore_errors: yes

- name: "[POST] Delete temporary SSH key"
  file:
    path: /tmp/id_ansible
    state: absent