---

- name: "[PRE] Export temporary SSH key"
  delegate_to: 127.0.0.1
  become: no
  changed_when: no
  copy: 
    content: "{{ ssh_private_key_file }}"
    dest: /tmp/id_ansible
    mode: '0600'

- name: "[PRE] Unlock SSH key"
  expect:
    command: ssh-add /tmp/id_ansible
    responses:
      passphrase: "{{ ssh_private_key_pass }}"
  delegate_to: 127.0.0.1
  become: no
  changed_when: no
  no_log: true

- name: Gathering facts
  setup: