apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  releaseName: sealed-secrets
  chart:
    spec:
      chart: sealed-secrets
      version: 2.6.1
      sourceRef:
        kind: HelmRepository
        name: bitnami-sealed-secrets
        namespace: flux-system
  interval: 30s
  values:
    fullnameOverride: sealed-secrets-controller