apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden
resources:
  - namespace.yaml

commonAnnotations:
  backup.velero.io/backup-volumes: data

commonLabels:
  app.kubernetes.io/name: vaultwarden

helmCharts:
- name: onechart
  includeCRDs: false
  valuesFile: values.yaml
  releaseName: vaultwarden
  version: 0.46.0
  repo: https://marcel-lambacher.github.io/onechart