apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden
resources:
  - namespace.yaml

commonAnnotations:
  backup.velero.io/backup-volumes: data

helmCharts:
- name: onechart
  includeCRDs: false
  valuesMerge: merge
  valuesFile: values.yaml
  valuesInline:
    image:
      repository: vaultwarden/server
      tag: latest
  releaseName: vaultwarden
  version: 0.46.0
  repo: https://marcel-lambacher.github.io/onechart