image:
  repository: vaultwarden/server
  tag: 1.25.1

resources:
  ignore: true

ingress:
  annotations:
    kubernetes.io/ingress.class: traefik
  host: vaultwarden.masterloft.k8s.marcel-lambacher.de
  # TLS is deactived in ingress, since default cert of traefik will take care of it (TLS per default)
  tlsEnabled: false

replicas: 1

containerPort: 80

probe:
  enabled: true
  path: "/"
  settings:
    initialDelaySeconds: 0
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 3
    failureThreshold: 3

livenessProbe:
  enabled: true
  path: "/"
  settings:
    initialDelaySeconds: 0
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 3
    failureThreshold: 3

volumes:
  - name: data
    path: /data
    size: 10Gi
    storageClass: longhorn-single-replica
    pvcAnnotations: 
      helm.sh/resource-policy: keep