apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - sealed-mariadb-init-secrets.json
  - sealed-mariadb-initdb-secret.json

commonAnnotations:
  backup.velero.io/backup-volumes: data

helmCharts:
- name: mariadb
  includeCRDs: false
  valuesFile: values.yaml
  releaseName: mariadb
  version: 11.3.5
  repo: https://charts.bitnami.com/bitnami