apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3proxy
  namespace: s3proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3proxy
  template:
    metadata:
      labels:
        app: s3proxy
    spec:
      containers:
      - name: s3proxy
        image: andrewgaul/s3proxy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: JCLOUDS_PROVIDER
          value: azureblob
        - name: JCLOUDS_IDENTITY
          value: stmasterloftveleroprod
        - name: JCLOUDS_CREDENTIAL
          valueFrom:
            secretKeyRef:
              name: s3proxy-env-values
              key: JCLOUDS_CREDENTIAL
        - name: S3PROXY_IDENTITY
          value: stmasterloftveleroprod
        - name: S3PROXY_CREDENTIAL
          valueFrom:
            secretKeyRef:
              name: s3proxy-env-values
              key: S3PROXY_CREDENTIAL
        - name: JCLOUDS_ENDPOINT
          value: https://stmasterloftveleroprod.blob.core.windows.net