apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard
  namespace: adguard
spec:
  releaseName: adguard
  chart:
    spec:
      chart: adguard-home
      version: 5.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system

  interval: 30s
  timeout: 10m0s

  install:
    timeout: 10m0s
    disableWait: false
    replace: true

  upgrade:
    timeout: 10m0s
    disableWait: false
    force: true

  values:
    persistence:
      config:
        enabled: true
        storageClass: local-path-ssd-auto-backup 

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.middlewares: authelia-forwardauth-authelia@kubernetescrd
        hosts:
          - host: adguard.cloud.lambacher.eu
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: adguard-adguard-home
                  port: 3000
        # TLS is deactived in ingress, since default cert of traefik will take care of it (TLS per default)
        # tls:
        # - hosts:
        #   - adguard.cloud.lambacher.eu
