- name: Provision masterloft local cluster
  hosts: masterloft-node-local
  gather_facts: no
  become: yes
  roles:
    - role: wireguard
      wireguard_config_template_path: 'masterloft-node-local/wg0.conf.j2'
    - role: k3s

  pre_tasks:
  - import_tasks: ./tasks/pre_tasks.yml
  post_tasks:
  - import_tasks: ./tasks/post_tasks.yml

- name: Provision masterloft remote tunnel
  hosts: masterloft-node-cloud
  gather_facts: no
  become: yes
  roles:
    - role: wireguard
      wireguard_config_template_path: 'masterloft-node-cloud/wg0.conf.j2'

  pre_tasks:
  - import_tasks: ./tasks/pre_tasks.yml
  post_tasks:
  - import_tasks: ./tasks/post_tasks.yml