# - name: Provision node-master cloud
#   hosts: masterloft-node-cloud
#   gather_facts: false
#   become: true
#   roles:
#     - role: wireguard
#       wireguard_config_template_path: 'masterloft-node-cloud/wg0.conf.j2'
#     - role: k3s/tooling
#     - role: k3s/master

#   pre_tasks:
#   - import_tasks: ./tasks/pre_tasks.yml
#   post_tasks:
#   - import_tasks: ./tasks/post_tasks.yml


- name: Provision masterloft node-worker on-premise
  hosts: masterloft-node-local
  gather_facts: false
  become: true
  roles:
    # - role: wireguard
    #   wireguard_config_template_path: 'masterloft-node-local/wg0.conf.j2'
    # - role: k3s/tooling
    - role: k3s/node-on-premise

  pre_tasks:
  - import_tasks: ./tasks/pre_tasks.yml
  post_tasks:
  - import_tasks: ./tasks/post_tasks.yml