apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sealed-secrets

helmCharts:
- name: sealed-secrets
  includeCRDs: true
  valuesFile: values.yaml
  releaseName: sealed-secrets
  version:  2.7.1
  repo: https://bitnami-labs.github.io/sealed-secrets