apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/apps/sealed-secrets
    repoURL: 'https://github.com/Marcel-Lambacher/Masterloft.git'
    targetRevision: feature/proxmox-migration
  syncPolicy:
    automated:
      prune: true
      selfHeal: true