apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging

helmCharts:
- name: loki-stack
  includeCRDs: false
  valuesFile: values.yaml
  releaseName: loki
  version: 2.8.3
  repo: https://grafana.github.io/helm-charts

# patches:
# - path: patch-logstash-statefulset.yaml
#   target:
#     kind: StatefulSet
#     labelSelector: app=loki-logstash

# helmCharts:
# - name: loki
#   includeCRDs: false
#   valuesFile: values.yaml
#   releaseName: loki
#   version: 3.2.0
#   repo: https://grafana.github.io/helm-charts