apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging

helmCharts:
- name: loki
  includeCRDs: false
  releaseName: loki
  version: 3.2.0
  repo: https://grafana.github.io/helm-charts