apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  releaseName: vaultwarden
  chart:
    spec:
      chart: vaultwarden
      version: 5.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  interval: 30s
  install:
    remediation:
      retries: 3
  values:
    podAnnotations:
      backup.velero.io/backup-volumes: config
  
    persistence:
      config:
        enabled: true
        storageClass: local-path-ssd-auto-backup 

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: vaultwarden.masterloft.k8s.marcel-lambacher.de
            paths:
              - path: /notifications/hub
                pathType: Exact
                service:
                  name: vaultwarden
                  port: 3012
              - path: /
                pathType: Prefix
                service:
                  name: vaultwarden
                  port: 80

        tls:
        - hosts:
          - vaultwarden.masterloft.k8s.marcel-lambacher.de
          secretName: masterloft-k8s-marcel-lambacher-de-tls
