apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: media
spec:
  releaseName: nzbget
  chart:
    spec:
      # chart: onechart 
      # version: 0.40.0
      # sourceRef:
      #   kind: HelmRepository
      #   name: onechart
      #   namespace: flux-system
      chart: charts/onechart
      sourceRef:
        kind: GitRepository
        name: onechart-fork
        namespace: flux-system


  interval: 30s
  timeout: 3m0s

  install:
    timeout: 3m0s
    disableWait: false
    replace: true

  upgrade:
    timeout: 3m0s
    disableWait: false
    force: true

  values:
    resources:
      ignore: true

    image:
      repository: linuxserver/nzbget
      tag: 21.1.20220908

    ingress:
      annotations:
        kubernetes.io/ingress.class: traefik
        # cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.middlewares: authelia-forwardauth-authelia@kubernetescrd, media-nzgbet-add-basic-auth-prefix-middleware@kubernetescrd
      host: nzbget.masterloft.k8s.marcel-lambacher.de
      tlsEnabled: true

    replicas: 1

    containerPort: 6789

    probe:
      enabled: false
      path: "/"
      settings:
        initialDelaySeconds: 0
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 3
        failureThreshold: 3

    livenessProbe:
      enabled: false
      path: "/"
      settings:
        initialDelaySeconds: 0
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 3
        failureThreshold: 3

    vars:
      # Disable basic authorization, since we're using authelia as an auth proxy
      NZBGET_USER: 'basic'
      NZBGET_PASS: 'auth'
      PUID: 1000
      PGID: 1000

    volumes:
      - name: data
        path: /data
        hostPath:
          path: /data

    existingFileSecrets:
      - name: config
        path: "/config/nzbget.conf"
        subPath: nzbget.conf