apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - sealed-nzbget-config.json
  - add-basic-auth-prefix-middleware.yaml

commonLabels:
  app.kubernetes.io/name: nzbget

helmCharts:
- name: onechart
  includeCRDs: false
  valuesFile: values.yaml
  releaseName: nzbget
  version: 0.46.0
  repo: https://marcel-lambacher.github.io/onechart