apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - sealed-nzbget-config.json
  - add-basic-auth-prefix-middleware.yaml

commonAnnotations:
  backup.velero.io/backup-volumes: data

helmCharts:
- name: onechart
  includeCRDs: false
  valuesMerge: merge
  valuesFile: values.yaml
  valuesInline:
    image:
      repository: linuxserver/nzbget
      tag: 21.1.20220908
  releaseName: nzbget
  version: 0.46.0
  repo: https://marcel-lambacher.github.io/onechart