image:
  repository: linuxserver/nzbget
  tag: 2021.11.25

resources:
  ignore: true

ingress:
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: authelia-forwardauth-authelia@kubernetescrd, media-nzgbet-add-basic-auth-prefix-middleware@kubernetescrd
  host: nzbget.masterloft.k8s.marcel-lambacher.de
  # TLS is deactived in ingress, since default cert of traefik will take care of it (TLS per default)
  tlsEnabled: false

replicas: 1

containerPort: 6789

probe:
  enabled: false
  path: "/"
  settings:
    initialDelaySeconds: 0
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 3
    failureThreshold: 3

livenessProbe:
  enabled: false
  path: "/"
  settings:
    initialDelaySeconds: 0
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 3
    failureThreshold: 3

vars:
  # Disable basic authorization, since we're using authelia as an auth proxy
  NZBGET_USER: 'basic'
  NZBGET_PASS: 'auth'
  PUID: 1000
  PGID: 1001

volumes:
  - name: data
    path: /data
    hostPath:
      path: /data

existingFileSecrets:
  - name: config
    path: "/config/nzbget.conf"
    subPath: nzbget.conf