---

- name: Download Helm
  get_url:
    url: 'https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz'
    dest: '/tmp/helm-{{ helm_version }}-linux-amd64.tar.gz'
    checksum: '{{ helm_checksum }}'
    force: no
    use_proxy: yes
    validate_certs: yes
    mode: 'u=rw,go=r'

- name: install unarchive module dependencies (apt, yum, dnf, zypper)
  become: true
  package:
    name:
      - tar
      - unzip
      - gzip
    state: present
  when: ansible_pkg_mgr in ('apt', 'yum', 'dnf', 'zypper')

- name: install Helm
  become: true
  unarchive:
    src: '/tmp/helm-{{ helm_version }}-linux-amd64.tar.gz'
    remote_src: yes
    dest: '/usr/local/bin'
    extra_opts:
      - '--strip-components=1'
    owner: root
    group: root
    mode: 'u=rwx,go=rx'
    creates: '/usr/local/bin/helm'