apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: database
spec:
  releaseName: postgresql
  chart:
    spec:
      chart: postgresql
      version: 11.8.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system

  interval: 30s
  timeout: 3m0s

  install:
    timeout: 3m0s
    disableWait: false
    replace: true

  upgrade:
    timeout: 3m0s
    disableWait: false
    force: true

  values:
    auth:
      database: marlam
      username: marlamm
      existingSecret: "postgresql"
      secretKeys:
        adminPasswordKey: postgresPassword
        userPasswordKey: postgresPassword
        replicationPasswordKey: postgresPassword

    global:
      storageClass: local-path-ssd-auto-backup
      postgresql:
        postgresqlDatabase: marlam
        postgresqlUsername: marlam
        auth:
          existingSecret: "postgresql"
          secretKeys:
            adminPasswordKey: postgres-password
            userPasswordKey: postgres-password
            replicationPasswordKey: postgres-password