apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: database
spec:
  releaseName: postgresql
  chart:
    spec:
      chart: bitnami/postgresql
      version: 14.5.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 30s
  values:
    global:
      storageClass: local-path-ssd-auto-backup
      auth:
        existingSecret: postgresql-secrets
      postgresqlorageClass:
        auth:
          username: marlam