---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 60m
  url: https://github.com/rancher/local-path-provisioner
  ref:
    tag: v0.0.22
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/deploy/chart/local-path-provisioner/