apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.11/manifests/install.yaml
  - ingress.yaml
  - bootstrap-app.yaml

patchesStrategicMerge:
  - argocd-cmd-params-cm-patch.yaml
  - argocd-cm-patch.yaml
